name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta, dev, main]
        version: [latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          channel: ${{ matrix.channel }}
          version: ${{ matrix.version }}
      - name: Flutter help
        run: flutter help
  test_version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [beta]
        version: [2.2.0-10.3.pre]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          channel: ${{ matrix.channel }}
          version: ${{ matrix.version }}
      - name: Flutter help
        run: flutter help

  test_dart:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta, dev, main]
        version: [latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          channel: ${{ matrix.channel }}
          version: ${{ matrix.version }}
      - name: Dart hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart
      - name: Dart test
        run: |
          dart create -t console-full consoleapp
          cd consoleapp
          dart test
      - name: Dart global activate + run
        run: |
          dart pub global activate stagehand
          mkdir testapp
          cd testapp
          stagehand console-simple
          dart pub get
          dart run
